version: '2'

services:
  jenkins-master:
    image: 172.17.16.118/ci/jenkins
    ports:
      - 48080:8080
      - 65000:50000
    volumes:
      - ./jenkins:/root/.jenkins
      - /var/run/docker.sock:/var/run/docker.sock
    restart: always
